Repository bazar-de-komi/terarea, pull requests merged in 2024-10, with the labels that each got.

#33 [UPDATE] the sql binding library
  app/back/db/data/terarea_skeleton_18_10_2024.sql
  app/back/server/.gitignore
  app/back/server/Makefile
  app/back/server/config.toml
  app/back/server/requirements.txt
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/crons.py
  app/back/server/src/lib/sql/sanitisation_functions.py
  app/back/server/src/lib/sql/sql_constants.py
  app/back/server/src/lib/sql/sql_manager.py
  app/back/server/src/lib/sql/time_manipulation.py
  app/back/server/tests/test_boilerplate_responses.py
  bonus/db/dumps/terarea_skeleton_18_10_2024.sql
Labels: unstable

#35 [FIX] sql binding for the back
  app/back/server/config.toml
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/sql/__init__.py
  app/back/server/src/lib/sql/sql_connections.py
  app/back/server/src/lib/sql/sql_constants.py
  app/back/server/src/lib/sql/sql_injection.py
  app/back/server/src/lib/sql/sql_manager.py
  app/back/server/src/lib/sql/sql_query_boilerplates.py
  app/back/server/src/lib/sql/sql_sanitisation_functions.py
  app/back/server/src/lib/sql/sql_time_manipulation.py
  docker-compose.yaml
Labels: untested

#106 [ADD] endpoint patch user
  app/back/server/src/lib/boilerplates/non_web.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/query_boilerplate.py
  app/back/server/tests/test_backend_endpoints.py
  app/back/server/tests/test_boilerplate_responses.py
Labels: enhancement, endpoint

#118 [ADD] endpoint delete user
  app/back/server/src/lib/boilerplates/non_web.py
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: enhancement, endpoint

#131 [ADD] the get user endpoint
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: enhancement, endpoint

#132 [ADD] endpoint /api/v1/user_id
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: enhancement, endpoint

#133 [ADD] endpoint POST /api/v1/logout
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: enhancement, endpoint

#134 [ADD] remaining user endpoints to the server
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: enhancement, endpoint

#140 [ADD] cron for renewing oaths
  app/back/db/data/terarea_skeleton_26_10_2024.sql
  app/back/server/config.toml
  app/back/server/dockerfile
  app/back/server/src/lib/boilerplates/responses.py
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/crons.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/src/lib/components/oauth_authentication.py
  app/back/server/tests/test_boilerplate_responses.py
  app/back/server/tests/test_paths.py
  app/front/mobile/dockerfile
  app/front/web/dockerfile
  bonus/db/dumps/terarea_skeleton_26_10_2024.sql
Labels: enhancement

#141 [FIX] my spelling misakes of oath. oath -> OAuth
  app/back/db/data/terarea_skeleton_26_10_2024.sql
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/crons.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/src/lib/components/oauth_authentication.py
  bonus/db/dumps/terarea_skeleton_26_10_2024.sql
Labels: fix

#173 [ADD] base for action parsing
  app/back/db/data/terarea_skeleton_27_10_2024.sql
  app/back/server/src/lib/actions/__init__.py
  app/back/server/src/lib/actions/action_management.py
  app/back/server/src/lib/actions/constants.py
  app/back/server/src/lib/actions/logger.py
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/trigger_management.py
  app/back/server/src/lib/actions/variables.py
  app/back/server/src/lib/components/constants.py
  app/back/server/src/lib/components/crons.py
  app/back/server/src/lib/components/runtime_data.py
  app/back/server/src/lib/server.py
  app/back/server/tests/test_action_logger.py
  app/back/server/tests/test_actions_constants.py
  app/back/server/tests/test_actions_main.py
  app/back/server/tests/test_actions_variables.py
  bonus/db/dumps/terarea_skeleton_27_10_2024.sql
  bonus/db/img/terarea_layout_27_10_2024.png
Labels: enhancement

#176 [ADD] parsing for checking if an action is being run or not
  app/back/db/data/terarea_skeleton_27_10_2024.sql
  app/back/server/src/lib/actions/__init__.py
  app/back/server/src/lib/actions/action_management.py
  app/back/server/src/lib/actions/constants.py
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/trigger_management.py
  app/back/server/src/lib/actions/variables.py
  app/back/server/src/lib/components/endpoints/bonus.py
  app/back/server/src/lib/components/endpoints_routes.py
  app/back/server/tests/test_actions_constants.py
  app/back/server/tests/test_actions_variables.py
  bonus/db/dumps/terarea_skeleton_27_10_2024.sql
Labels: enhancement

#182 [UPDATE] the consequences column to be of type null
  app/back/db/data/terarea_skeleton_29_10_2024.sql
  bonus/db/dumps/terarea_skeleton_29_10_2024.sql
Labels: enhancement

#184 [UPDATE] server and the .gitignore
  .gitignore
  app/back/server/src/lib/actions/action_management.py
  app/back/server/src/lib/actions/constants.py
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/query_boilerplate.py
  app/back/server/src/lib/actions/status_check.py
  app/back/server/src/lib/actions/trigger_management.py
  app/back/server/src/lib/actions/variables.py
  app/back/server/tests/test_actions_variables.py
Labels: enhancement

#186 [UPDATE] the full stack content
  .gitignore
  app/back/db/data/terarea_skeleton_29_10_2024.sql
  app/back/server/src/lib/actions/action_management.py
  app/back/server/src/lib/actions/constants.py
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/query_boilerplate.py
  app/back/server/src/lib/actions/status_check.py
  app/back/server/src/lib/actions/trigger_management.py
  app/back/server/src/lib/actions/variables.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/src/lib/components/oauth_authentication.py
  app/back/server/tests/test_actions_variables.py
  app/front/web/lib/querier.ts
  app/front/web/package-lock.json
  app/front/web/package.json
  app/front/web/public/index.html
  app/front/web/src/components/AppHeader.vue
  app/front/web/src/components/AppletBoardTile.vue
  app/front/web/src/components/CancelButton.vue
  app/front/web/src/components/CreateApplet-Comp/IfBlock.vue
  app/front/web/src/components/CreateApplet-Comp/ThenBlock.vue
  app/front/web/src/components/Details-Applet/CompConnectButton.vue
  app/front/web/src/components/Details-Applet/CompDescription.vue
  app/front/web/src/components/Details-Applet/CompSource.vue
  app/front/web/src/components/Details-Applet/CompStats.vue
  app/front/web/src/components/Details-Applet/CompTitle.vue
  app/front/web/src/components/Details-Applet/UserCount.vue
  app/front/web/src/components/Details-Service/CompConnectButton.vue
  app/front/web/src/components/Details-Service/CompDescription.vue
  app/front/web/src/components/Details-Service/CompSource.vue
  app/front/web/src/components/Details-Service/CompStats.vue
  app/front/web/src/components/Details-Service/CompTitle.vue
  app/front/web/src/components/Details-Service/UserCount.vue
  app/front/web/src/components/ServiceBoardTile.vue
  app/front/web/src/router/index.ts
  app/front/web/src/store/applets.ts
  app/front/web/src/views/AppletDetails.vue
  app/front/web/src/views/CreateApplet.vue
  app/front/web/src/views/auth/SignInView.vue
  app/front/web/src/views/auth/SignUpView.vue
  app/front/web/src/views/board/AreaPage-All.vue
  app/front/web/src/views/board/AreaPage-Applet.vue
  app/front/web/src/views/board/AreaPage-Service.vue
  app/front/web/src/views/tile-information/AppletDetails.vue
  app/front/web/src/views/tile-information/ServiceDetails.vue
  bonus/.idea/.gitignore
  bonus/.idea/Terraria.iml
  bonus/.idea/misc.xml
  bonus/.idea/modules.xml
  bonus/.idea/other.xml
  bonus/.idea/vcs.xml
  bonus/db/dumps/terarea_skeleton_29_10_2024.sql
Labels: enhancement, endpoint, fix

#188 [FIX] errors in the register endpoint
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
Labels: endpoint, fix

#190 [UPDATE] the database architecture
  app/back/db/data/terarea_skeleton_30_10_2024.sql
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/query_boilerplate.py
  app/back/server/src/lib/actions/trigger_management.py
  bonus/db/dumps/terarea_skeleton_30_10_2024.sql
  docs/query_sample_files/node/actions_content.json
  docs/query_sample_files/node/actions_content_new.json
  docs/query_sample_files/trigger/trigger_content.json
  docs/query_sample_files/trigger/trigger_content_new.json
Labels: enhancement

#191 [UPDATE] Database architecture
  app/back/db/data/terarea_skeleton_30_10_2024.sql
  app/back/server/src/lib/actions/main.py
  app/back/server/src/lib/actions/query_boilerplate.py
  app/back/server/src/lib/actions/trigger_management.py
  app/back/server/src/lib/components/endpoints/user_endpoints.py
  app/back/server/tests/constants.py
  app/back/server/tests/test_backend_endpoints.py
  app/front/mobile/assets/font.ttf
  app/front/mobile/back-endConnection/querier.ts
  app/front/mobile/package-lock.json
  app/front/mobile/package.json
  app/front/mobile/src/Navigation/index.tsx
  app/front/mobile/src/components/AppletsBox/appletBox.tsx
  app/front/mobile/src/components/SocialAuthButton/socialAuthButton.tsx
  app/front/mobile/src/components/StoreData/storeData.tsx
  app/front/mobile/src/screens/AppletsScreen/AppletsScreen.tsx
  app/front/mobile/src/screens/AppletsScreen/ServicesDetails.tsx
  app/front/mobile/src/screens/AppletsScreen/ServicesScreen.tsx
  app/front/mobile/src/screens/Authentication/ForgotPassword/forgotPassword.tsx
  app/front/mobile/src/screens/Authentication/ForgotPassword/newPassword.tsx
  app/front/mobile/src/screens/Authentication/OAuth/index.tsx
  app/front/mobile/src/screens/Authentication/OAuth/oauth.tsx
  app/front/mobile/src/screens/Authentication/SignIn/signIn.tsx
  app/front/mobile/src/screens/Authentication/SignUp/index.tsx
  app/front/mobile/src/screens/Authentication/SignUp/signUp.tsx
  app/front/mobile/src/screens/Create/create.tsx
  bonus/db/dumps/terarea_skeleton_30_10_2024.sql
  docs/query_sample_files/node/actions_content.json
  docs/query_sample_files/node/actions_content_new.json
  docs/query_sample_files/trigger/trigger_content.json
  docs/query_sample_files/trigger/trigger_content_new.json
Labels: enhancement, fix

#199 [UPDATE] rename terarea_skeleton SQL file and add colour column to Services table
  app/back/db/data/terarea_skeleton_1_11_2024.sql
  bonus/db/dumps/terarea_skeleton_1_11_2024.sql
Labels: enhancement, fix
